### ISSUE TITLE
show more information in the popup modal 

### ISSUE THREAD

**Issue by gurpreetg** [gurpreetg/Make-WaterlooWorks-Great-Again#25]
- since we already have the scrolling implemented, we might as well show more information

**Comment by peygar** [comment]
We need to trim some of the whitespace in the modal (extra newline characters and <br> element)

**Comment by gurpreetg** [comment]
We already have enough information in the popup modal! I think adding anything else would make it too "crowded". https://github.com/gurpreetg/Make-WaterlooWorks-Great-Again/pull/48 was the last thing we added! Closing this issue
