### ISSUE TITLE
cannot open the info page 

### ISSUE THREAD

**Issue by iFun** [gurpreetg/Make-WaterlooWorks-Great-Again#46]
chrome-extension://mlekdinlcaggpokncinbmomaplhbjpmb/js/jquery.min.js:4 XMLHttpRequest cannot load javascript:void(0);. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

This is the error I got 
The pop-up just keep spinning

**Comment by peygar** [comment]
Orbis changed the way they were loading the job posting page. Should be fixed in this commit:
https://github.com/gurpreetg/Make-WaterlooWorks-Great-Again/commit/40d62281a26543475db9691d7d631c1d5bd38ebc
Thanks for the heads up!
